# TODO: move to rhino api _config folder (currently)

---
Name: DataFetcher-config
Only:
  moduleexists: 'symbiote/silverstripe-queuedjobs'
---
Symbiote\QueuedJobs\DataObjects\QueuedJobDescriptor:
  extensions:
    - 'emteknetnz\DataFetcher\Extensions\QueuedJobDescriptorExtension'
